builtins_data = '''
[variables]
$ALL_GROUPS
$ALL_EVENTS
%CC
$CC_NUM
%CC_TOUCHED
$DISTANCE_BAR_START
$DURATION_BAR
$DURATION_QUARTER
$DURATION_EIGHTH
$DURATION_SIXTEENTH
$DURATION_QUARTER_TRIPLET
$DURATION_EIGHTH_TRIPLET
$DURATION_SIXTEENTH_TRIPLET
$ENGINE_UPTIME
$EVENT_ID
$EVENT_NOTE
$EVENT_VELOCITY
%GROUPS_AFFECTED
%KEY_DOWN
%KEY_DOWN_OCT
$MARK_1
$MARK_2
$MARK_3
$MARK_4
$MARK_5
$MARK_6
$MARK_7
$MARK_8
$MARK_9
$MARK_10
$MARK_11
$MARK_12
$MARK_13
$MARK_14
$MARK_15
$MARK_16
$MARK_17
$MARK_18
$MARK_19
$MARK_20
$MARK_21
$MARK_22
$MARK_23
$MARK_24
$MARK_25
$MARK_26
$MARK_27
$MARK_28
%NOTE_DURATION
$NOTE_HELD
$SIGNATURE_NUM
$SIGNATURE_DENOM
$NUM_GROUPS
$NUM_ZONES
$PLAYED_VOICES_INST
$PLAYED_VOICES_TOTAL
%EVENT_PAR
$VCC_PITCH_BEND
$RPN_ADDRESS
$RPN_VALUE
$GET_FOLDER_INSTALL_DIR
$GET_FOLDER_LIBRARY_DIR
$GET_FOLDER_PATCH_DIR
$ENGINE_PAR_EFFECT_TYPE
$ENGINE_PAR_EFFECT_SUBTYPE
$ENGINE_PAR_SEND_EFFECT_TYPE
$ENGINE_PAR_INTMOD_TYPE
$ENGINE_PAR_INTMOD_SUBTYPE
$ENGINE_PAR_VOLUME
$ENGINE_PAR_PAN
$ENGINE_PAR_TUNE
$ENGINE_PAR_SMOOTH
$ENGINE_PAR_FORMANT
$ENGINE_PAR_SPEED
$ENGINE_PAR_GRAIN_LENGTH
$ENGINE_PAR_SLICE_ATTACK
$ENGINE_PAR_SLICE_RELEASE
$ENGINE_PAR_TRANSIENT_SIZE
$ENGINE_PAR_CUTOFF
$ENGINE_PAR_RESONANCE
$ENGINE_PAR_EFFECT_BYPASS
$ENGINE_PAR_FILTER_SHIFTB
$ENGINE_PAR_FILTER_SHIFTC
$ENGINE_PAR_FILTER_RESB
$ENGINE_PAR_FILTER_RESC
$ENGINE_PAR_FILTER_TYPEA
$ENGINE_PAR_FILTER_TYPEB
$ENGINE_PAR_FILTER_TYPEC
$ENGINE_PAR_FILTER_BYPA
$ENGINE_PAR_FILTER_BYPB
$ENGINE_PAR_FILTER_BYPC
$ENGINE_PAR_FILTER_GAIN
$ENGINE_PAR_FREQ1
$ENGINE_PAR_BW1
$ENGINE_PAR_GAIN1
$ENGINE_PAR_FREQ2
$ENGINE_PAR_BW2
$ENGINE_PAR_GAIN2
$ENGINE_PAR_FREQ3
$ENGINE_PAR_BW3
$ENGINE_PAR_GAIN3
$ENGINE_PAR_INSERT_EFFECT_OUTPUT_GAIN
$ENGINE_PAR_THRESHOLD
$ENGINE_PAR_RATIO
$ENGINE_PAR_COMP_ATTACK
$ENGINE_PAR_COMP_DECAY
$ENGINE_PAR_LIM_IN_GAIN
$ENGINE_PAR_LIM_RELEASE
$ENGINE_PAR_SP_OFFSET_DISTANCE
$ENGINE_PAR_SP_OFFSET_AZIMUTH
$ENGINE_PAR_SP_OFFSET_X
$ENGINE_PAR_SP_OFFSET_Y
$ENGINE_PAR_SP_LFE_VOLUME
$ENGINE_PAR_SP_SIZE
$ENGINE_PAR_SP_DIVERGENCE
$ENGINE_PAR_SHAPE
$ENGINE_PAR_BITS
$ENGINE_PAR_FREQUENCY
$ENGINE_PAR_NOISELEVEL
$ENGINE_PAR_NOISECOLOR
$ENGINE_PAR_STEREO
$ENGINE_PAR_STEREO_PAN
$ENGINE_PAR_DRIVE
$ENGINE_PAR_DAMPING
$ENGINE_PAR_SENDLEVEL_0
$ENGINE_PAR_SENDLEVEL_1
$ENGINE_PAR_SENDLEVEL_2
$ENGINE_PAR_SENDLEVEL_3
$ENGINE_PAR_SENDLEVEL_4
$ENGINE_PAR_SENDLEVEL_5
$ENGINE_PAR_SENDLEVEL_6
$ENGINE_PAR_SENDLEVEL_7
$ENGINE_PAR_SEND_EFFECT_BYPASS
$ENGINE_PAR_SEND_EFFECT_DRY_LEVEL
$ENGINE_PAR_SEND_EFFECT_OUTPUT_GAIN
$ENGINE_PAR_PH_DEPTH
$ENGINE_PAR_PH_SPEED
$ENGINE_PAR_PH_PHASE
$ENGINE_PAR_PH_FEEDBACK
$ENGINE_PAR_FL_DEPTH
$ENGINE_PAR_FL_SPEED
$ENGINE_PAR_FL_PHASE
$ENGINE_PAR_FL_FEEDBACK
$ENGINE_PAR_FL_COLOR
$ENGINE_PAR_CH_DEPTH
$ENGINE_PAR_CH_SPEED
$ENGINE_PAR_CH_PHASE
$ENGINE_PAR_RV_PREDELAY
$ENGINE_PAR_RV_SIZE
$ENGINE_PAR_RV_COLOUR
$ENGINE_PAR_RV_STEREO
$ENGINE_PAR_RV_DAMPING
$ENGINE_PAR_DL_TIME
$ENGINE_PAR_DL_DAMPING
$ENGINE_PAR_DL_PAN
$ENGINE_PAR_DL_FEEDBACK
$ENGINE_PAR_IRC_PREDELAY
$ENGINE_PAR_IRC_LENGTH_RATIO_ER
$ENGINE_PAR_IRC_FREQ_LOWPASS_ER
$ENGINE_PAR_IRC_FREQ_HIGHPASS_ER
$ENGINE_PAR_IRC_LENGTH_RATIO_LR
$ENGINE_PAR_IRC_FREQ_LOWPASS_LR
$ENGINE_PAR_IRC_FREQ_HIGHPASS_LR
$ENGINE_PAR_GN_GAIN
$ENGINE_PAR_EXTMOD_INTENSITY
$ENGINE_PAR_INTMOD_INTENSITY
$ENGINE_PAR_INTMOD_BYPASS
$ENGINE_PAR_ATK_CURVE
$ENGINE_PAR_ATTACK
$ENGINE_PAR_HOLD
$ENGINE_PAR_DECAY
$ENGINE_PAR_SUSTAIN
$ENGINE_PAR_RELEASE
$ENGINE_PAR_DECAY1
$ENGINE_PAR_BREAK
$ENGINE_PAR_DECAY2
$ENGINE_PAR_INTMOD_FREQUENCY
$ENGINE_PAR_LFO_DELAY
$ENGINE_PAR_INTMOD_PULSEWIDTH
$ENGINE_PAR_LFO_SINE
$ENGINE_PAR_LFO_RECT
$ENGINE_PAR_LFO_TRI
$ENGINE_PAR_LFO_SAW
$ENGINE_PAR_LFO_RAND
$EFFECT_TYPE_FILTER
$EFFECT_TYPE_COMPRESSOR
$EFFECT_TYPE_LIMITER
$EFFECT_TYPE_INVERTER
$EFFECT_TYPE_SURROUND_PANNER
$EFFECT_TYPE_SHAPER
$EFFECT_TYPE_LOFI
$EFFECT_TYPE_STEREO
$EFFECT_TYPE_DISTORTION
$EFFECT_TYPE_SEND_LEVELS
$EFFECT_TYPE_PHASER
$EFFECT_TYPE_CHORUS
$EFFECT_TYPE_FLANGER
$EFFECT_TYPE_REVERB
$EFFECT_TYPE_DELAY
$EFFECT_TYPE_IRC
$EFFECT_TYPE_GAINER
$EFFECT_TYPE_NONE
$FILTER_TYPE_LP1POLE
$FILTER_TYPE_HP1POLE
$FILTER_TYPE_BP2POLE
$FILTER_TYPE_LP2POLE
$FILTER_TYPE_HP2POLE
$FILTER_TYPE_LP4POLE
$FILTER_TYPE_HP4POLE
$FILTER_TYPE_BP4POLE
$FILTER_TYPE_BR4POLE
$FILTER_TYPE_LP6POLE
$FILTER_TYPE_PHASER
$FILTER_TYPE_VOWELA
$FILTER_TYPE_VOWELB
$FILTER_TYPE_PRO52
$FILTER_TYPE_LADDER
$FILTER_TYPE_VERSATILE
$FILTER_TYPE_EQ1BAND
$FILTER_TYPE_EQ2BAND
$FILTER_TYPE_EQ3BAND
$KNOB_UNIT_NONE
$KNOB_UNIT_DB
$KNOB_UNIT_HZ
$KNOB_UNIT_PERCENT
$KNOB_UNIT_MS
$KNOB_UNIT_OCT
$REF_GROUP_IDX
%GROUPS_SELECTED
$ENGINE_PAR_START_CRITERIA_MODE
$ENGINE_PAR_START_CRITERIA_KEY_MIN
$ENGINE_PAR_START_CRITERIA_KEY_MAX
$ENGINE_PAR_START_CRITERIA_CONTROLLER
$ENGINE_PAR_START_CRITERIA_CC_MIN
$ENGINE_PAR_START_CRITERIA_CC_MAX
$ENGINE_PAR_START_CRITERIA_CYCLE_CLASS
$ENGINE_PAR_START_CRITERIA_ZONE_IDX
$ENGINE_PAR_START_CRITERIA_SLICE_IDX
$ENGINE_PAR_START_CRITERIA_SEQ_ONLY
$ENGINE_PAR_START_CRITERIA_NEXT_CRIT
$START_CRITERIA_NONE
$START_CRITERIA_ON_KEY
$START_CRITERIA_ON_CONTROLLER
$START_CRITERIA_CYCLE_ROUND_ROBIN
$START_CRITERIA_CYCLE_RANDOM
$START_CRITERIA_SLICE_TRIGGER
$START_CRITERIA_AND_NEXT
$START_CRITERIA_AND_NOT_NEXT
$START_CRITERIA_OR_NEXT
$ENGINE_PAR_RELEASE_TRIGGER
$INTMOD_TYPE_LFO
$INTMOD_TYPE_ENVELOPE
$LFO_TYPE_SINE
$INTMOD_TYPE_NONE
$MIDI_CHANNEL
$MIDI_COMMAND
$MIDI_BYTE_1
$MIDI_BYTE_2
$IDX_OFFSET_EXT_MOD
$KNOB_UNIT_ST
$ENGINE_PAR_SK_TONE
$ENGINE_PAR_SK_DRIVE
$ENGINE_PAR_SK_BASS
$ENGINE_PAR_SK_BRIGHT
$ENGINE_PAR_SK_MIX
$ENGINE_PAR_RT_SPEED
$ENGINE_PAR_RT_BALANCE
$ENGINE_PAR_RT_ACCEL_HI
$ENGINE_PAR_RT_ACCEL_LO
$ENGINE_PAR_RT_DISTANCE
$ENGINE_PAR_RT_MIX
$ENGINE_PAR_TW_VOLUME
$ENGINE_PAR_TW_TREBLE
$ENGINE_PAR_TW_MID
$ENGINE_PAR_TW_BASS
$ENGINE_PAR_CB_SIZE
$ENGINE_PAR_CB_AIR
$ENGINE_PAR_CB_TREBLE
$ENGINE_PAR_CB_BASS
$ENGINE_PAR_CABINET_TYPE
$MOD_TARGET_INVERT_SOURCE
$ENGINE_PAR_MOD_TARGET_INTENSITY
$HIDE_PART_BG
$HIDE_PART_VALUE
$HIDE_PART_TITLE
$HIDE_PART_MOD_LIGHT
$VCC_MONO_AT
$HIDE_PART_NOTHING
$HIDE_WHOLE_CONTROL
$EVENT_STATUS_INACTIVE
$EVENT_STATUS_NOTE_QUEUE
$EVENT_STATUS_MIDI_QUEUE
$KEY_COLOR_NONE
$KEY_COLOR_WHITE
$KEY_COLOR_RED
$KEY_COLOR_ORANGE
$KEY_COLOR_LIGHT_ORANGE
$KEY_COLOR_WARM_YELLOW
$KEY_COLOR_YELLOW
$KEY_COLOR_LIME
$KEY_COLOR_GREEN
$KEY_COLOR_MINT
$KEY_COLOR_CYAN
$KEY_COLOR_TURQUOISE
$KEY_COLOR_BLUE
$KEY_COLOR_PLUM
$KEY_COLOR_BLACK
$KEY_COLOR_VIOLET
$KEY_COLOR_PURPLE
$KEY_COLOR_MAGENTA
$KEY_COLOR_FUCHSIA
$KEY_COLOR_INACTIVE
$EVENT_PAR_0
$EVENT_PAR_1
$EVENT_PAR_2
$EVENT_PAR_3
$EVENT_PAR_VOLUME
$EVENT_PAR_PAN
$EVENT_PAR_TUNE
$EVENT_PAR_NOTE
$EVENT_PAR_VELOCITY
$KSP_TIMER
$CONTROL_PAR_HIDE
$CONTROL_PAR_POS_X
$CONTROL_PAR_POS_Y
$CONTROL_PAR_HELP
$CONTROL_PAR_LABEL
$CONTROL_PAR_UNIT
$CONTROL_PAR_BAR_COLOR
$CONTROL_PAR_DEFAULT_VALUE
$CONTROL_PAR_FONT_TYPE
$CONTROL_PAR_GRID_HEIGHT
$CONTROL_PAR_GRID_WIDTH
$CONTROL_PAR_GRID_X
$CONTROL_PAR_GRID_Y
$CONTROL_PAR_HEIGHT
$CONTROL_PAR_MAX_VALUE
$CONTROL_PAR_MIN_VALUE
$CONTROL_PAR_MOUSE_BEHAVIOUR
$CONTROL_PAR_NONE
$CONTROL_PAR_PICTURE
$CONTROL_PAR_PICTURE_STATE
$CONTROL_PAR_SHOW_ARROWS
$CONTROL_PAR_TEXT
$CONTROL_PAR_TEXTLINE
$CONTROL_PAR_TEXTPOS_Y
$CONTROL_PAR_TEXT_ALIGNMENT
$CONTROL_PAR_VALUE
$CONTROL_PAR_WIDTH
$CONTROL_PAR_ZERO_LINE_COLOR
$CONTROL_PAR_BG_COLOR
$CONTROL_PAR_OFF_COLOR
$CONTROL_PAR_ON_COLOR
$CONTROL_PAR_OVERLOAD_COLOR
$CONTROL_PAR_PEAK_COLOR
$CONTROL_PAR_VERTICAL
$CONTROL_PAR_BASEPATH
$CONTROL_PAR_COLUMN_WIDTH
$CONTROL_PAR_FILEPATH
$CONTROL_PAR_FILE_TYPE
$CONTROL_PAR_SELECTED_ITEM_IDX
$CONTROL_PAR_NUM_ITEMS
$CONTROL_PAR_AUTOMATION_NAME
$CONTROL_PAR_KEY_ALT
$CONTROL_PAR_KEY_CONTROL
$CONTROL_PAR_KEY_SHIFT
$CONTROL_PAR_ALLOW_AUTOMATION
$CONTROL_PAR_DND_BEHAVIOUR
$EFFECT_TYPE_AET_FILTER
$EFFECT_TYPE_CABINET
$INTMOD_TYPE_ENVELOPE
$INTMOD_TYPE_ENV_FOLLOW
$INTMOD_TYPE_GLIDE
$INTMOD_TYPE_LFO
$INTMOD_TYPE_STEPMOD
$EFFECT_TYPE_ROTATOR
$EFFECT_TYPE_SKREAMER
$EFFECT_TYPE_TWANG
$ENGINE_PAR_EXP_FILTER_AMOUNT
$ENGINE_PAR_EXP_FILTER_MORPH
$ENGINE_PAR_GLIDE_COEF
$ENV_TYPE_AHDSR
$ENV_TYPE_DBD
$ENV_TYPE_FLEX
$EVENT_PAR_ALLOW_GROUP
$EVENT_PAR_MIDI_BYTE_1
$EVENT_PAR_MIDI_BYTE_2
$EVENT_PAR_MIDI_CHANNEL
$EVENT_PAR_MIDI_COMMAND
$GET_FOLDER_FACTORY_DIR
$INST_ICON_ID
$LFO_TYPE_MULTI
$LFO_TYPE_RANDOM
$LFO_TYPE_RECTANGLE
$LFO_TYPE_SAWTOOTH
$LFO_TYPE_TRIANGLE
$MIDI_COMMAND_CC
$MIDI_COMMAND_MONO_AT
$MIDI_COMMAND_NOTE_OFF
$MIDI_COMMAND_NOTE_ON
$MIDI_COMMAND_NRPN
$MIDI_COMMAND_PITCH_BEND
$MIDI_COMMAND_POLY_AT
$MIDI_COMMAND_PROGRAM_CHANGE
$MIDI_COMMAND_RPN
$VALUE_EDIT_MODE_NOTE_NAMES
$CURRENT_SCRIPT_SLOT
$ENGINE_PAR_SENDLEVEL_SMOOTHED_0
$ENGINE_PAR_SENDLEVEL_SMOOTHED_1
$ENGINE_PAR_SENDLEVEL_SMOOTHED_2
$ENGINE_PAR_SENDLEVEL_SMOOTHED_3
$ENGINE_PAR_SENDLEVEL_SMOOTHED_4
$ENGINE_PAR_SENDLEVEL_SMOOTHED_5
$ENGINE_PAR_SENDLEVEL_SMOOTHED_6
$ENGINE_PAR_SENDLEVEL_SMOOTHED_7
$ENGINE_PAR_OUTPUT_CHANNEL
$NUM_OUTPUT_CHANNELS
$CURRENT_SCRIPT_SLOT
$EVENT_PAR_SOURCE
$MIDI_CHANNEL
%POLY_AT
$POLY_AT_NUM
$INST_WALLPAPER_ID
$NI_SONG_POSITION
$UI_WAVEFORM_USE_SLICES
$UI_WAVEFORM_USE_TABLE
$UI_WAVEFORM_TABLE_IS_BIPOLAR
$UI_WAVEFORM_USE_MIDI_DRAG
$UI_WF_PROP_PLAY_CURSOR
$UI_WF_PROP_FLAGS
$UI_WF_PROP_TABLE_VAL
$UI_WF_PROP_TABLE_IDX_HIGHLIGHT
$UI_WF_PROP_MIDI_DRAG_START_NOTE
$EVENT_PAR_PLAY_POS
$EVENT_PAR_ZONE_ID
$NI_SIGNAL_TRANSP_STOP
$NI_SIGNAL_TRANSP_START
$NI_SIGNAL_TIMER_MS
$NI_SIGNAL_TIMER_BEAT
$NI_SIGNAL_TYPE
$NI_CALLBACK_ID
$NI_CALLBACK_TYPE
$NI_CB_TYPE_NOTE
$NI_CB_TYPE_RELEASE
$NI_CB_TYPE_CONTROLLER
$NI_CB_TYPE_POLY_AT
$NI_CB_TYPE_INIT
$NI_CB_TYPE_UI_CONTROL
$NI_CB_TYPE_UI_UPDATE
$NI_CB_TYPE_PGS
$NI_CB_TYPE_MIDI_IN
$NI_CB_TYPE_RPN
$NI_CB_TYPE_NRPN
$NI_CB_TYPE_LISTENER
$ENGINE_PAR_TP_GAIN
$ENGINE_PAR_TP_WARMTH
$ENGINE_PAR_TP_HF_ROLLOFF
$ENGINE_PAR_TR_INPUT
$ENGINE_PAR_TR_ATTACK
$ENGINE_PAR_TR_SUSTAIN
$ENGINE_PAR_SEQ_LF_GAIN
$ENGINE_PAR_SEQ_LF_FREQ
$ENGINE_PAR_SEQ_LF_BELL
$ENGINE_PAR_SEQ_LMF_GAIN
$ENGINE_PAR_SEQ_LMF_FREQ
$ENGINE_PAR_SEQ_LMF_Q
$ENGINE_PAR_SEQ_HMF_GAIN
$ENGINE_PAR_SEQ_HMF_FREQ
$ENGINE_PAR_SEQ_HMF_Q
$ENGINE_PAR_SEQ_HF_GAIN
$ENGINE_PAR_SEQ_HF_FREQ
$ENGINE_PAR_SEQ_HF_BELL
$ENGINE_PAR_SCOMP_THRESHOLD
$ENGINE_PAR_SCOMP_RATIO
$ENGINE_PAR_SCOMP_ATTACK
$ENGINE_PAR_SCOMP_RELEASE
$ENGINE_PAR_SCOMP_MAKEUP
$ENGINE_PAR_SCOMP_MIX
$NI_ASYNC_ID
$NI_ASYNC_EXIT_STATUS
$NI_CB_TYPE_ASYNC_OUT
$NI_BUS_OFFSET
$NI_FILE_TYPE_ARRAY
$NI_FILE_TYPE_AUDIO
$NI_FILE_TYPE_MIDI
$ENGINE_PAR_GAIN
$ENGINE_PAR_BANDWIDTH
$ENGINE_PAR_FORMANT_TALK
$ENGINE_PAR_FORMANT_SHARP
$ENGINE_PAR_FORMANT_SIZE
$EFFECT_TYPE_TRANS_MASTER
$EFFECT_TYPE_BUS_COMP
$EFFECT_TYPE_TAPE_SAT
$FILTER_TYPE_DAFT_LP
$FILTER_TYPE_SV_LP1
$FILTER_TYPE_SV_LP2
$FILTER_TYPE_SV_LP4
$FILTER_TYPE_LDR_LP1
$FILTER_TYPE_LDR_LP2
$FILTER_TYPE_LDR_LP3
$FILTER_TYPE_LDR_LP4
$FILTER_TYPE_AR_LP2
$FILTER_TYPE_AR_LP4
$FILTER_TYPE_AR_LP24
$FILTER_TYPE_SV_HP1
$FILTER_TYPE_SV_HP2
$FILTER_TYPE_SV_HP4
$FILTER_TYPE_LDR_HP1
$FILTER_TYPE_LDR_HP2
$FILTER_TYPE_LDR_HP3
$FILTER_TYPE_LDR_HP4
$FILTER_TYPE_AR_HP2
$FILTER_TYPE_AR_HP4
$FILTER_TYPE_AR_HP24
$FILTER_TYPE_DAFT_HP
$FILTER_TYPE_SV_BP2
$FILTER_TYPE_SV_BP4
$FILTER_TYPE_LDR_BP2
$FILTER_TYPE_LDR_BP4
$FILTER_TYPE_AR_BP2
$FILTER_TYPE_AR_BP4
$FILTER_TYPE_AR_BP24
$FILTER_TYPE_SV_NOTCH4
$FILTER_TYPE_LDR_PEAK
$FILTER_TYPE_LDR_NOTCH
$FILTER_TYPE_SV_PAR_LPHP
$FILTER_TYPE_SV_PAR_BPBP
$FILTER_TYPE_SV_SER_LPHP
$FILTER_TYPE_FORMANT_1
$FILTER_TYPE_FORMANT_2
$EFFECT_TYPE_SOLID_GEQ
$ENGINE_PAR_GAIN
$ENGINE_PAR_BANDWIDTH
$ENGINE_PAR_FORMANT_TALK
$ENGINE_PAR_FORMANT_SHARP
$ENGINE_PAR_FORMANT_SIZE
$EFFECT_TYPE_TRANS_MASTER
$EFFECT_TYPE_BUS_COMP
$EFFECT_TYPE_TAPE_SAT
$FILTER_TYPE_DAFT_LP
$FILTER_TYPE_SV_LP1
$FILTER_TYPE_SV_LP2
$FILTER_TYPE_SV_LP4
$FILTER_TYPE_LDR_LP1
$FILTER_TYPE_LDR_LP2
$FILTER_TYPE_LDR_LP3
$FILTER_TYPE_LDR_LP4
$FILTER_TYPE_AR_LP2
$FILTER_TYPE_AR_LP4
$FILTER_TYPE_AR_LP24
$FILTER_TYPE_SV_HP1
$FILTER_TYPE_SV_HP2
$FILTER_TYPE_SV_HP4
$FILTER_TYPE_LDR_HP1
$FILTER_TYPE_LDR_HP2
$FILTER_TYPE_LDR_HP3
$FILTER_TYPE_LDR_HP4
$FILTER_TYPE_AR_HP2
$FILTER_TYPE_AR_HP4
$FILTER_TYPE_AR_HP24
$FILTER_TYPE_DAFT_HP
$FILTER_TYPE_SV_BP2
$FILTER_TYPE_SV_BP4
$FILTER_TYPE_LDR_BP2
$FILTER_TYPE_LDR_BP4
$FILTER_TYPE_AR_BP2
$FILTER_TYPE_AR_BP4
$FILTER_TYPE_AR_BP24
$FILTER_TYPE_SV_NOTCH4
$FILTER_TYPE_LDR_PEAK
$FILTER_TYPE_LDR_NOTCH
$FILTER_TYPE_SV_PAR_LPHP
$FILTER_TYPE_SV_PAR_BPBP
$FILTER_TYPE_SV_SER_LPHP
$FILTER_TYPE_FORMANT_1
$FILTER_TYPE_FORMANT_2
$EFFECT_TYPE_SOLID_GEQ
$NI_TRANSPORT_RUNNING
$INST_LIB_PIC_ONE_ID
$INST_LIB_PIC_TWO_ID
$INST_LIB_COPYRIGHT_ID
$INST_LIB_DESCRIPTION_ID
$ENGINE_PAR_ENVELOPE_ORDER
$ENGINE_PAR_FORMANT_SHIFT
$CONTROL_PAR_VERTICAL
$CONTROL_PAR_OFF_COLOR
$CONTROL_PAR_ON_COLOR
$CONTROL_PAR_OVERLOAD_COLOR
$CONTROL_PAR_PEAK_COLOR
$ENGINE_PAR_JMP_PREAMP
$ENGINE_PAR_JMP_BASS
$ENGINE_PAR_JMP_MID
$ENGINE_PAR_JMP_TREBLE
$ENGINE_PAR_JMP_MASTER
$ENGINE_PAR_JMP_PRESENCE
$ENGINE_PAR_JMP_HIGAIN
$ENGINE_PAR_JMP_MONO
$ENGINE_PAR_FCOMP_INPUT
$ENGINE_PAR_FCOMP_RATIO
$ENGINE_PAR_FCOMP_ATTACK
$ENGINE_PAR_FCOMP_RELEASE
$ENGINE_PAR_FCOMP_MAKEUP
$ENGINE_PAR_FCOMP_MIX
$EFFECT_TYPE_JUMP
$EFFECT_TYPE_FB_COMP

[functions]
SET_CONDITION(<condition>)
RESET_CONDITION(<condition>)
USE_CODE_IF(<condition>)
USE_CODE_IF_NOT(<condition>)
END_USE_CODE()
exit()
set_text(<variable>,<text>)
add_text_line(<variable>,<text>)
add_menu_item(<variable>,<text>,<number>)
move_control(<variable>,<xpos>,<ypos>)
abs(<expression>):integer
by_marks(<bit-mark>):integer
change_note(<ID-number>,<new-note-number>)
change_pan(<ID-number>,<panorama>,<relative-bit>)
change_time_with_pitch(<ID-number>,<time>):integer
change_tune(<ID-number>,<tune-amount>,<relative-bit>)
change_velo(<ID-number>,<new-velocity-number>)
change_vol(<ID-number>,<volume>,<relative-bit>)
dec(<expression>):integer
fade_in(<ID-number>,<fade-time>)
fade_out(<ID-number>,<fade-time>,<stop-voice>)
in_range(<expression>,<lower>,<upper>):boolean
ignore_controller()
ignore_event(<ID-number>)
inc(<expression>)
make_persistent(<variable>)
message(<number variable or text>)
note_off(<ID-number>)
play_note(<note-number>,<velocity>,<sample-offset>,<duration>):integer
random(<min>,<max>):integer
_reset_rls_trig_counter(<note>)
set_controller(<controller-number>,<controller-value>)
set_event_mark(<ID-number>,<bit-mark>)
sh_left(<expression>,<amount>):integer
sh_right(<expression>,<amount>):integer
wait(<wait-time>)
_will_never_terminate(<event-id>)
disallow_group(<group-index>)
allow_group(<group-index>)
find_group(<group-name>):integer
group_name(<group-index>):string
sort(<array-variable>,<direction>)
num_elements(<array-variable>):integer
search(<array-variable>,<value>):integer
array_equal(<array-variable>,<array-variable>):boolean
_num_slices(<group-index>):integer
_slice_length(<group-index>,<slice-index>):integer
_slice_start(<group-index>,<slice-index>):integer
_slice_idx_loop_start(<group-index>,<loop-index>):integer
_slice_idx_loop_end(<group-index>,<loop-index>):integer
_slice_loop_count(<group-index>,<loop-index>):integer
dont_use_machine_mode(<ID-number>):integer
set_event_par(<ID-number>,<index>,<value>)
set_event_par_arr(<ID-number>,<parameter>,<value>,<group-idx>)
make_perfview()
msb(<variable>):integer
lsb(<variable>):integer
set_rpn(<address>,<value>)
set_nrpn(<address>,<value>)
_set_engine_par(<parameter>,<value>,<group>,<slot>,<generic>)
_get_engine_par(<parameter>,<group>,<slot>,<generic>):integer
_load_ir_sample(<file name>,<slot>,<generic>):integer
load_ir_sample(<file name>,<slot>,<generic>):integer
_get_folder(<path variable>):string
_read_persistent_var(<variable>)
set_knob_unit(<knob-variable>,<unit>)
set_knob_label(<knob-variable>,<text>)
_get_engine_par_disp(<parameter>,<group>,<slot>,<generic>):string
set_knob_defval(<knob-variable>,<value>)
cc_delivery_request(<controller-number>)
unload_slot(<unknown>)
reset_engine()
redirect_midi(<unknown>)
redirect_output(<unknown>)
set_midi(<channel>,<command>,<byte1>,<byte2>)
get_engine_par_m(<unknown>)
set_engine_par_m(<unknown>)
load_ir_sample_m(<unknown>)
load_patch(<text>,<channel>)
_delay_event_for_loading_slots(<unknown>)
ignore_midi()
_set_skin_offset(<offset>)
_pgs_create_key(<key-id>,<size>)
_pgs_key_exists(<key-id>):boolean
_pgs_set_key_val(<key-id>,<index>,<value>)
_pgs_get_key_val(<key-id>,<index>):integer
find_target(<group-idx>,<mod-idx>,<target-name>):integer
find_mod(<group-idx>,<mod-name>):integer
set_table_steps_shown(<array-variable>,<num-steps>)
set_control_help(<variable>,<text>)
event_status(<ID-number>):integer
hide_part(<variable>,<value>)
get_event_par(<ID-number>,<parameter>):integer
get_event_par_arr(<ID-number>,<parameter>,<group-idx>):integer
set_event_par_arr(<ID-number>,<parameter>,<value>,<group-idx>)
purge_group(<group-index>,<mode>)
get_control_par(<ui-ID>,<control-parameter>):integer
get_control_par_str(<ui-ID>,<control-parameter>):string
get_control_arr(<ui-ID>,<control-parameter>):integer
set_control_par(<ui-ID>,<control-parameter>,<value>)
set_control_par_str(<ui-ID>,<control-parameter>,<text>)
set_control_arr(<ui-ID>,<control-parameter>,<value>)
get_ui_id(<variable>):integer
move_control_px(<variable>,<x-position>,<y-position>)
set_control_help(<variable>,<text>)
set_key_color(<note-number>,<key-color-constant>)
set_script_title(<text>)
set_ui_height(<height>)
set_ui_height_px(<height>)
reset_ksp_timer()
reset_rls_trig_counter(<note>)
will_never_terminate(<event-id>)
num_slices(<group-index>):integer
slice_length(<group-index>,<slice-index>):integer
slice_start(<group-index>,<slice-index>):integer
slice_idx_loop_start(<group-index>,<loop-index>):integer
slice_idx_loop_end(<group-index>,<loop-index>):integer
slice_loop_count(<group-index>,<loop-index>):integer
set_engine_par(<parameter>,<value>,<group>,<slot>,<generic>)
get_engine_par(<parameter>,<group>,<slot>,<generic>):integer
get_folder(<path variable>):string
read_persistent_var(<variable>)
get_engine_par_disp(<parameter>,<group>,<slot>,<generic>):string
set_skin_offset(<offset>)
pgs_create_key(<key-id>,<size>)
pgs_key_exists(<key-id>):boolean
pgs_set_key_val(<key-id>,<index>,<value>)
pgs_get_key_val(<key-id>,<index>):integer
output_channel_name(<output-number>):integer
delete_event_mark(<ID-number>,<bit-mark>)
get_event_ids(<array-variable>)
find_zone(<sample-name>):integer
num_slices_zone(<zone-id>):integer
get_sample_length(<zone-ID>):integer
zone_slice_length(<zone-ID>,<slice-index>):integer
zone_slice_start(<zone-ID>,<slice-index>):integer
zone_slice_idx_loop_start(<zone-ID>,<loop-index>):integer
zone_slice_idx_loop_end(<zone-ID>,<loop-index>):integer
zone_slice_loop_count(<zone-ID>,<loop-index>):integer
attach_zone(<waveform>,<zone-id>,<parameter>)
get_ui_wf_property(<waveform>,<property>,<index>):integer
set_ui_wf_property(<waveform>,<property>,<index>,<value>)
set_listener(<signal_type>,<parameter>)
change_listener_par(<signal_type>,<parameter>)
save_array(<array-or-string-array-variable>,<mode>):integer
save_array_str(<array-or-string-array-variable>,<path-text>):integer
load_array(<array-or-string-array-variable>,<mode>):integer
load_array_str(<array-or-string-array-variable>,<path-text>):integer
get_purge_state(<group-index>):integer
ms_to_ticks(<microseconds>):integer
ticks_to_ms(<ticks>):integer
fs_get_filename(<ui-ID>,<return-parameter>):string
fs_navigate(<ui-ID>,<direction>)
load_midi_file(<path variable>):integer
mf_get_first(<track-index>)
mf_get_next(<track-index>)
mf_get_next_at(<track-index>,<pos>)
mf_get_last(<track-index>)
mf_get_prev(<track-index>)
mf_get_prev_at(<track-index>,<pos>)
mf_set_byte_one(<par>)
mf_set_byte_two(<par>)
mf_set_byte_one(<par>)
mf_set_command(<par>)
mf_set_pos(<par>)
mf_set_channel(<midi-channel>)
save_midi_file(<path variable>):integer
stop_wait(<callbackID>,<par>)
wait_ticks(<wait-time>)
pgs_create_str_key(<key-id>)
pgs_str_key_exists(<key-id>):boolean
pgs_set_str_key_val(<key-id>,<text>)
pgs_get_str_key_val(<key-id>):string
mf_get_num_tracks():integer
mf_get_channel():integer
mf_get_command():integer
mf_get_byte_one():integer
mf_get_byte_two():integer
mf_get_pos():integer
mf_get_track_idx():integer
attach_level_meter(<uiID>,<groupIdx>,<slotIdx>,<channelIdx>,<busIdx>)
get_menu_item_value(<menu_id>,<index>):integer
get_menu_item_str(<menu_id>,<index>):string
get_menu_item_visibility(<menu_id>,<index>):integer
set_menu_item_value(<menu_id>,<index>,<value>)
set_menu_item_str(<menu_id>,<index>,<text>)
set_menu_item_visibility(<menu_id>,<index>,<visibility>)
show_library_tab()
set_control_par_arr(<ui-ID>,<control-parameter>,<value>,<index>)
get_control_par_arr(<ui-ID>,<control-parameter>,<index>):integer
mf_set_length(<par>)
mf_get_length():integer
get_engine_par_disp_m(<unknown>):string
set_engine_par_disp_m(<unknown>)
mf_reset()
set_key_name(<key-number>,<key-name>)
set_keyrange(<key-number1>,<key-number2>,<range-name>)
remove_keyrange(<key-number>)
set_key_pressed_support(<value>)
set_key_pressed(<key-number>,<value>)
make_instr_persistent(<variable>)
set_snapshot_type(<type>)

[functions_with_forced_parenthesis]
mf_reset

[keywords]
declare
const
on
init
note
release
controller
ui_control
poly_at
rpn
nrpn
end
while
for
to
downto
step
if
else
select
case
function
macro
property
family
import
ui_update
_pgs_changed
pgs_changed
midi_in
call
on init
on note
on release
on midi_in
on rpn
on nrpn
on controller
on ui_control
on ui_update
on poly_at
on async_complete
on pgs_changed
on listener
on persistence_changed
end on
end function
end if
end for
end while
end select
end family
end macro
end property
taskfunc
end taskfunc
override
and
or
not
var
out

[string_typed_control_parameters]
$CONTROL_PAR_HELP
$CONTROL_PAR_LABEL
$CONTROL_PAR_PICTURE
$CONTROL_PAR_TEXT
$CONTROL_PAR_TEXTLINE
$CONTROL_PAR_BASEPATH
$CONTROL_PAR_FILEPATH
$CONTROL_PAR_AUTOMATION_NAME
'''
