builtins_data = '''
[variables]
$ALL_EVENTS
$ALL_GROUPS
$CC_NUM
$CONTROL_PAR_ALLOW_AUTOMATION
$CONTROL_PAR_AUTOMATION_ID
$CONTROL_PAR_AUTOMATION_NAME
$CONTROL_PAR_BAR_COLOR
$CONTROL_PAR_BASEPATH
$CONTROL_PAR_BG_COLOR
$CONTROL_PAR_COLUMN_WIDTH
$CONTROL_PAR_DEFAULT_VALUE
$CONTROL_PAR_DND_BEHAVIOUR
$CONTROL_PAR_FILE_TYPE
$CONTROL_PAR_FILEPATH
$CONTROL_PAR_FONT_TYPE
$CONTROL_PAR_GRID_HEIGHT
$CONTROL_PAR_GRID_WIDTH
$CONTROL_PAR_GRID_X
$CONTROL_PAR_GRID_Y
$CONTROL_PAR_HEIGHT
$CONTROL_PAR_HELP
$CONTROL_PAR_HIDE
$CONTROL_PAR_KEY_ALT
$CONTROL_PAR_KEY_CONTROL
$CONTROL_PAR_KEY_SHIFT
$CONTROL_PAR_LABEL
$CONTROL_PAR_MAX_VALUE
$CONTROL_PAR_MIN_VALUE
$CONTROL_PAR_MOUSE_BEHAVIOUR
$CONTROL_PAR_NONE
$CONTROL_PAR_NUM_ITEMS
$CONTROL_PAR_OFF_COLOR
$CONTROL_PAR_ON_COLOR
$CONTROL_PAR_OVERLOAD_COLOR
$CONTROL_PAR_PEAK_COLOR
$CONTROL_PAR_PICTURE
$CONTROL_PAR_PICTURE_STATE
$CONTROL_PAR_POS_X
$CONTROL_PAR_POS_Y
$CONTROL_PAR_SELECTED_ITEM_IDX
$CONTROL_PAR_SHOW_ARROWS
$CONTROL_PAR_TEXT
$CONTROL_PAR_TEXT_ALIGNMENT
$CONTROL_PAR_TEXTLINE
$CONTROL_PAR_TEXTPOS_Y
$CONTROL_PAR_UNIT
$CONTROL_PAR_VALUE
$CONTROL_PAR_VERTICAL
$CONTROL_PAR_WIDTH
$CONTROL_PAR_ZERO_LINE_COLOR
$CURRENT_EVENT
$CURRENT_SCRIPT_SLOT
$DISTANCE_BAR_START
$DURATION_BAR
$DURATION_EIGHTH
$DURATION_EIGHTH_TRIPLET
$DURATION_QUARTER
$DURATION_QUARTER_TRIPLET
$DURATION_SIXTEENTH
$DURATION_SIXTEENTH_TRIPLET
$EFFECT_TYPE_AET_FILTER
$EFFECT_TYPE_BUS_COMP
$EFFECT_TYPE_CABINET
$EFFECT_TYPE_CHORUS
$EFFECT_TYPE_COMPRESSOR
$EFFECT_TYPE_DELAY
$EFFECT_TYPE_DISTORTION
$EFFECT_TYPE_FB_COMP
$EFFECT_TYPE_FILTER
$EFFECT_TYPE_FLANGER
$EFFECT_TYPE_GAINER
$EFFECT_TYPE_INVERTER
$EFFECT_TYPE_IRC
$EFFECT_TYPE_JUMP
$EFFECT_TYPE_LIMITER
$EFFECT_TYPE_LOFI
$EFFECT_TYPE_NONE
$EFFECT_TYPE_PHASER
$EFFECT_TYPE_REVERB
$EFFECT_TYPE_ROTATOR
$EFFECT_TYPE_SEND_LEVELS
$EFFECT_TYPE_SHAPER
$EFFECT_TYPE_SKREAMER
$EFFECT_TYPE_SOLID_GEQ
$EFFECT_TYPE_STEREO
$EFFECT_TYPE_SURROUND_PANNER
$EFFECT_TYPE_TAPE_SAT
$EFFECT_TYPE_TRANS_MASTER
$EFFECT_TYPE_TWANG
$ENGINE_PAR_ATK_CURVE
$ENGINE_PAR_ATTACK
$ENGINE_PAR_BANDWIDTH
$ENGINE_PAR_BITS
$ENGINE_PAR_BREAK
$ENGINE_PAR_BW1
$ENGINE_PAR_BW2
$ENGINE_PAR_BW3
$ENGINE_PAR_CABINET_TYPE
$ENGINE_PAR_CB_AIR
$ENGINE_PAR_CB_BASS
$ENGINE_PAR_CB_SIZE
$ENGINE_PAR_CB_TREBLE
$ENGINE_PAR_CH_DEPTH
$ENGINE_PAR_CH_PHASE
$ENGINE_PAR_CH_SPEED
$ENGINE_PAR_COMP_ATTACK
$ENGINE_PAR_COMP_DECAY
$ENGINE_PAR_CUTOFF
$ENGINE_PAR_DAMPING
$ENGINE_PAR_DECAY
$ENGINE_PAR_DECAY1
$ENGINE_PAR_DECAY2
$ENGINE_PAR_DL_DAMPING
$ENGINE_PAR_DL_FEEDBACK
$ENGINE_PAR_DL_PAN
$ENGINE_PAR_DL_TIME
$ENGINE_PAR_DRIVE
$ENGINE_PAR_EFFECT_BYPASS
$ENGINE_PAR_EFFECT_SUBTYPE
$ENGINE_PAR_EFFECT_TYPE
$ENGINE_PAR_ENVELOPE_ORDER
$ENGINE_PAR_EXP_FILTER_AMOUNT
$ENGINE_PAR_EXP_FILTER_MORPH
$ENGINE_PAR_EXTMOD_INTENSITY
$ENGINE_PAR_FCOMP_ATTACK
$ENGINE_PAR_FCOMP_INPUT
$ENGINE_PAR_FCOMP_MAKEUP
$ENGINE_PAR_FCOMP_MIX
$ENGINE_PAR_FCOMP_RATIO
$ENGINE_PAR_FCOMP_RELEASE
$ENGINE_PAR_FILTER_BYPA
$ENGINE_PAR_FILTER_BYPB
$ENGINE_PAR_FILTER_BYPC
$ENGINE_PAR_FILTER_GAIN
$ENGINE_PAR_FILTER_RESB
$ENGINE_PAR_FILTER_RESC
$ENGINE_PAR_FILTER_SHIFTB
$ENGINE_PAR_FILTER_SHIFTC
$ENGINE_PAR_FILTER_TYPEA
$ENGINE_PAR_FILTER_TYPEB
$ENGINE_PAR_FILTER_TYPEC
$ENGINE_PAR_FL_COLOR
$ENGINE_PAR_FL_DEPTH
$ENGINE_PAR_FL_FEEDBACK
$ENGINE_PAR_FL_PHASE
$ENGINE_PAR_FL_SPEED
$ENGINE_PAR_FORMANT
$ENGINE_PAR_FORMANT_SHARP
$ENGINE_PAR_FORMANT_SHIFT
$ENGINE_PAR_FORMANT_SIZE
$ENGINE_PAR_FORMANT_TALK
$ENGINE_PAR_FREQ1
$ENGINE_PAR_FREQ2
$ENGINE_PAR_FREQ3
$ENGINE_PAR_FREQUENCY
$ENGINE_PAR_GAIN
$ENGINE_PAR_GAIN1
$ENGINE_PAR_GAIN2
$ENGINE_PAR_GAIN3
$ENGINE_PAR_GLIDE_COEF
$ENGINE_PAR_GN_GAIN
$ENGINE_PAR_GRAIN_LENGTH
$ENGINE_PAR_HOLD
$ENGINE_PAR_INSERT_EFFECT_OUTPUT_GAIN
$ENGINE_PAR_INTMOD_BYPASS
$ENGINE_PAR_INTMOD_FREQUENCY
$ENGINE_PAR_INTMOD_INTENSITY
$ENGINE_PAR_INTMOD_PULSEWIDTH
$ENGINE_PAR_INTMOD_SUBTYPE
$ENGINE_PAR_INTMOD_TYPE
$ENGINE_PAR_IRC_FREQ_HIGHPASS_ER
$ENGINE_PAR_IRC_FREQ_HIGHPASS_LR
$ENGINE_PAR_IRC_FREQ_LOWPASS_ER
$ENGINE_PAR_IRC_FREQ_LOWPASS_LR
$ENGINE_PAR_IRC_LENGTH_RATIO_ER
$ENGINE_PAR_IRC_LENGTH_RATIO_LR
$ENGINE_PAR_IRC_PREDELAY
$ENGINE_PAR_JMP_BASS
$ENGINE_PAR_JMP_HIGAIN
$ENGINE_PAR_JMP_MASTER
$ENGINE_PAR_JMP_MID
$ENGINE_PAR_JMP_MONO
$ENGINE_PAR_JMP_PREAMP
$ENGINE_PAR_JMP_PRESENCE
$ENGINE_PAR_JMP_TREBLE
$ENGINE_PAR_LFO_DELAY
$ENGINE_PAR_LFO_RAND
$ENGINE_PAR_LFO_RECT
$ENGINE_PAR_LFO_SAW
$ENGINE_PAR_LFO_SINE
$ENGINE_PAR_LFO_TRI
$ENGINE_PAR_LIM_IN_GAIN
$ENGINE_PAR_LIM_RELEASE
$ENGINE_PAR_MOD_TARGET_INTENSITY
$ENGINE_PAR_NOISECOLOR
$ENGINE_PAR_NOISELEVEL
$ENGINE_PAR_OUTPUT_CHANNEL
$ENGINE_PAR_PAN
$ENGINE_PAR_PH_DEPTH
$ENGINE_PAR_PH_FEEDBACK
$ENGINE_PAR_PH_PHASE
$ENGINE_PAR_PH_SPEED
$ENGINE_PAR_RATIO
$ENGINE_PAR_RELEASE
$ENGINE_PAR_RELEASE_TRIGGER
$ENGINE_PAR_RESONANCE
$ENGINE_PAR_RT_ACCEL_HI
$ENGINE_PAR_RT_ACCEL_LO
$ENGINE_PAR_RT_BALANCE
$ENGINE_PAR_RT_DISTANCE
$ENGINE_PAR_RT_MIX
$ENGINE_PAR_RT_SPEED
$ENGINE_PAR_RV_COLOUR
$ENGINE_PAR_RV_DAMPING
$ENGINE_PAR_RV_PREDELAY
$ENGINE_PAR_RV_SIZE
$ENGINE_PAR_RV_STEREO
$ENGINE_PAR_SCOMP_ATTACK
$ENGINE_PAR_SCOMP_MAKEUP
$ENGINE_PAR_SCOMP_MIX
$ENGINE_PAR_SCOMP_RATIO
$ENGINE_PAR_SCOMP_RELEASE
$ENGINE_PAR_SCOMP_THRESHOLD
$ENGINE_PAR_SEND_EFFECT_BYPASS
$ENGINE_PAR_SEND_EFFECT_DRY_LEVEL
$ENGINE_PAR_SEND_EFFECT_OUTPUT_GAIN
$ENGINE_PAR_SEND_EFFECT_TYPE
$ENGINE_PAR_SENDLEVEL_0
$ENGINE_PAR_SENDLEVEL_1
$ENGINE_PAR_SENDLEVEL_2
$ENGINE_PAR_SENDLEVEL_3
$ENGINE_PAR_SENDLEVEL_4
$ENGINE_PAR_SENDLEVEL_5
$ENGINE_PAR_SENDLEVEL_6
$ENGINE_PAR_SENDLEVEL_7
$ENGINE_PAR_SENDLEVEL_SMOOTHED_0
$ENGINE_PAR_SENDLEVEL_SMOOTHED_1
$ENGINE_PAR_SENDLEVEL_SMOOTHED_2
$ENGINE_PAR_SENDLEVEL_SMOOTHED_3
$ENGINE_PAR_SENDLEVEL_SMOOTHED_4
$ENGINE_PAR_SENDLEVEL_SMOOTHED_5
$ENGINE_PAR_SENDLEVEL_SMOOTHED_6
$ENGINE_PAR_SENDLEVEL_SMOOTHED_7
$ENGINE_PAR_SEQ_HF_BELL
$ENGINE_PAR_SEQ_HF_FREQ
$ENGINE_PAR_SEQ_HF_GAIN
$ENGINE_PAR_SEQ_HMF_FREQ
$ENGINE_PAR_SEQ_HMF_GAIN
$ENGINE_PAR_SEQ_HMF_Q
$ENGINE_PAR_SEQ_LF_BELL
$ENGINE_PAR_SEQ_LF_FREQ
$ENGINE_PAR_SEQ_LF_GAIN
$ENGINE_PAR_SEQ_LMF_FREQ
$ENGINE_PAR_SEQ_LMF_GAIN
$ENGINE_PAR_SEQ_LMF_Q
$ENGINE_PAR_SHAPE
$ENGINE_PAR_SK_BASS
$ENGINE_PAR_SK_BRIGHT
$ENGINE_PAR_SK_DRIVE
$ENGINE_PAR_SK_MIX
$ENGINE_PAR_SK_TONE
$ENGINE_PAR_SLICE_ATTACK
$ENGINE_PAR_SLICE_RELEASE
$ENGINE_PAR_SMOOTH
$ENGINE_PAR_SP_DIVERGENCE
$ENGINE_PAR_SP_LFE_VOLUME
$ENGINE_PAR_SP_OFFSET_AZIMUTH
$ENGINE_PAR_SP_OFFSET_DISTANCE
$ENGINE_PAR_SP_OFFSET_X
$ENGINE_PAR_SP_OFFSET_Y
$ENGINE_PAR_SP_SIZE
$ENGINE_PAR_SPEED
$ENGINE_PAR_START_CRITERIA_CC_MAX
$ENGINE_PAR_START_CRITERIA_CC_MIN
$ENGINE_PAR_START_CRITERIA_CONTROLLER
$ENGINE_PAR_START_CRITERIA_CYCLE_CLASS
$ENGINE_PAR_START_CRITERIA_KEY_MAX
$ENGINE_PAR_START_CRITERIA_KEY_MIN
$ENGINE_PAR_START_CRITERIA_MODE
$ENGINE_PAR_START_CRITERIA_NEXT_CRIT
$ENGINE_PAR_START_CRITERIA_SEQ_ONLY
$ENGINE_PAR_START_CRITERIA_SLICE_IDX
$ENGINE_PAR_START_CRITERIA_ZONE_IDX
$ENGINE_PAR_STEREO
$ENGINE_PAR_STEREO_PAN
$ENGINE_PAR_SUSTAIN
$ENGINE_PAR_THRESHOLD
$ENGINE_PAR_TP_GAIN
$ENGINE_PAR_TP_HF_ROLLOFF
$ENGINE_PAR_TP_WARMTH
$ENGINE_PAR_TR_ATTACK
$ENGINE_PAR_TR_INPUT
$ENGINE_PAR_TR_SUSTAIN
$ENGINE_PAR_TRANSIENT_SIZE
$ENGINE_PAR_TUNE
$ENGINE_PAR_TW_BASS
$ENGINE_PAR_TW_MID
$ENGINE_PAR_TW_TREBLE
$ENGINE_PAR_TW_VOLUME
$ENGINE_PAR_VOLUME
$ENGINE_UPTIME
$ENV_TYPE_AHDSR
$ENV_TYPE_DBD
$ENV_TYPE_FLEX
$EVENT_ID
$EVENT_NOTE
$EVENT_PAR_0
$EVENT_PAR_1
$EVENT_PAR_2
$EVENT_PAR_3
$EVENT_PAR_ALLOW_GROUP
$EVENT_PAR_ID
$EVENT_PAR_MIDI_BYTE_1
$EVENT_PAR_MIDI_BYTE_2
$EVENT_PAR_MIDI_CHANNEL
$EVENT_PAR_MIDI_COMMAND
$EVENT_PAR_NOTE
$EVENT_PAR_NOTE_LENGTH
$EVENT_PAR_PAN
$EVENT_PAR_PLAY_POS
$EVENT_PAR_POS
$EVENT_PAR_SOURCE
$EVENT_PAR_TRACK_NR
$EVENT_PAR_TUNE
$EVENT_PAR_VELOCITY
$EVENT_PAR_VOLUME
$EVENT_PAR_ZONE_ID
$EVENT_STATUS_INACTIVE
$EVENT_STATUS_MIDI_QUEUE
$EVENT_STATUS_NOTE_QUEUE
$EVENT_VELOCITY
$FILTER_TYPE_AR_BP2
$FILTER_TYPE_AR_BP24
$FILTER_TYPE_AR_BP4
$FILTER_TYPE_AR_HP2
$FILTER_TYPE_AR_HP24
$FILTER_TYPE_AR_HP4
$FILTER_TYPE_AR_LP2
$FILTER_TYPE_AR_LP24
$FILTER_TYPE_AR_LP4
$FILTER_TYPE_BP2POLE
$FILTER_TYPE_BP4POLE
$FILTER_TYPE_BR4POLE
$FILTER_TYPE_DAFT_HP
$FILTER_TYPE_DAFT_LP
$FILTER_TYPE_EQ1BAND
$FILTER_TYPE_EQ2BAND
$FILTER_TYPE_EQ3BAND
$FILTER_TYPE_FORMANT_1
$FILTER_TYPE_FORMANT_2
$FILTER_TYPE_HP1POLE
$FILTER_TYPE_HP2POLE
$FILTER_TYPE_HP4POLE
$FILTER_TYPE_LADDER
$FILTER_TYPE_LDR_BP2
$FILTER_TYPE_LDR_BP4
$FILTER_TYPE_LDR_HP1
$FILTER_TYPE_LDR_HP2
$FILTER_TYPE_LDR_HP3
$FILTER_TYPE_LDR_HP4
$FILTER_TYPE_LDR_LP1
$FILTER_TYPE_LDR_LP2
$FILTER_TYPE_LDR_LP3
$FILTER_TYPE_LDR_LP4
$FILTER_TYPE_LDR_NOTCH
$FILTER_TYPE_LDR_PEAK
$FILTER_TYPE_LP1POLE
$FILTER_TYPE_LP2POLE
$FILTER_TYPE_LP4POLE
$FILTER_TYPE_LP6POLE
$FILTER_TYPE_PHASER
$FILTER_TYPE_PRO52
$FILTER_TYPE_SV_BP2
$FILTER_TYPE_SV_BP4
$FILTER_TYPE_SV_HP1
$FILTER_TYPE_SV_HP2
$FILTER_TYPE_SV_HP4
$FILTER_TYPE_SV_LP1
$FILTER_TYPE_SV_LP2
$FILTER_TYPE_SV_LP4
$FILTER_TYPE_SV_NOTCH4
$FILTER_TYPE_SV_PAR_BPBP
$FILTER_TYPE_SV_PAR_LPHP
$FILTER_TYPE_SV_SER_LPHP
$FILTER_TYPE_VERSATILE
$FILTER_TYPE_VOWELA
$FILTER_TYPE_VOWELB
$GET_FOLDER_FACTORY_DIR
$GET_FOLDER_INSTALL_DIR
$GET_FOLDER_LIBRARY_DIR
$GET_FOLDER_PATCH_DIR
$HIDE_PART_BG
$HIDE_PART_MOD_LIGHT
$HIDE_PART_NOTHING
$HIDE_PART_TITLE
$HIDE_PART_VALUE
$HIDE_WHOLE_CONTROL
$IDX_OFFSET_EXT_MOD
$INST_ICON_ID
$INST_LIB_COPYRIGHT_ID
$INST_LIB_DESCRIPTION_ID
$INST_LIB_PIC_ONE_ID
$INST_LIB_PIC_TWO_ID
$INST_WALLPAPER_ID
$INTMOD_TYPE_ENV_FOLLOW
$INTMOD_TYPE_ENVELOPE
$INTMOD_TYPE_GLIDE
$INTMOD_TYPE_LFO
$INTMOD_TYPE_NONE
$INTMOD_TYPE_STEPMOD
$KEY_COLOR_BLACK
$KEY_COLOR_BLUE
$KEY_COLOR_CYAN
$KEY_COLOR_FUCHSIA
$KEY_COLOR_GREEN
$KEY_COLOR_INACTIVE
$KEY_COLOR_LIGHT_ORANGE
$KEY_COLOR_LIME
$KEY_COLOR_MAGENTA
$KEY_COLOR_MINT
$KEY_COLOR_NONE
$KEY_COLOR_ORANGE
$KEY_COLOR_PLUM
$KEY_COLOR_PURPLE
$KEY_COLOR_RED
$KEY_COLOR_TURQUOISE
$KEY_COLOR_VIOLET
$KEY_COLOR_WARM_YELLOW
$KEY_COLOR_WHITE
$KEY_COLOR_YELLOW
$KNOB_UNIT_DB
$KNOB_UNIT_HZ
$KNOB_UNIT_MS
$KNOB_UNIT_NONE
$KNOB_UNIT_OCT
$KNOB_UNIT_PERCENT
$KNOB_UNIT_ST
$KSP_TIMER
$LFO_TYPE_MULTI
$LFO_TYPE_RANDOM
$LFO_TYPE_RECTANGLE
$LFO_TYPE_SAWTOOTH
$LFO_TYPE_SINE
$LFO_TYPE_TRIANGLE
$MARK_1
$MARK_2
$MARK_3
$MARK_4
$MARK_5
$MARK_6
$MARK_7
$MARK_8
$MARK_9
$MARK_10
$MARK_11
$MARK_12
$MARK_13
$MARK_14
$MARK_15
$MARK_16
$MARK_17
$MARK_18
$MARK_19
$MARK_20
$MARK_21
$MARK_22
$MARK_23
$MARK_24
$MARK_25
$MARK_26
$MARK_27
$MARK_28
$MIDI_BYTE_1
$MIDI_BYTE_2
$MIDI_CHANNEL
$MIDI_COMMAND
$MIDI_COMMAND_CC
$MIDI_COMMAND_MONO_AT
$MIDI_COMMAND_NOTE_OFF
$MIDI_COMMAND_NOTE_ON
$MIDI_COMMAND_NRPN
$MIDI_COMMAND_PITCH_BEND
$MIDI_COMMAND_POLY_AT
$MIDI_COMMAND_PROGRAM_CHANGE
$MIDI_COMMAND_RPN
$MOD_TARGET_INVERT_SOURCE
$NI_ASYNC_EXIT_STATUS
$NI_ASYNC_ID
$NI_BUS_OFFSET
$NI_CALLBACK_ID
$NI_CALLBACK_TYPE
$NI_CB_TYPE_ASYNC_OUT
$NI_CB_TYPE_CONTROLLER
$NI_CB_TYPE_INIT
$NI_CB_TYPE_LISTENER
$NI_CB_TYPE_MIDI_IN
$NI_CB_TYPE_NOTE
$NI_CB_TYPE_NRPN
$NI_CB_TYPE_PGS
$NI_CB_TYPE_POLY_AT
$NI_CB_TYPE_RELEASE
$NI_CB_TYPE_RPN
$NI_CB_TYPE_UI_CONTROL
$NI_CB_TYPE_UI_UPDATE
$NI_FILE_TYPE_ARRAY
$NI_FILE_TYPE_AUDIO
$NI_FILE_TYPE_MIDI
$NI_KEY_TYPE_DEFAULT
$NI_KEY_TYPE_CONTROL
$NI_KEY_TYPE_NONE
$NI_SIGNAL_TIMER_BEAT
$NI_SIGNAL_TIMER_MS
$NI_SIGNAL_TRANSP_START
$NI_SIGNAL_TRANSP_STOP
$NI_SIGNAL_TYPE
$NI_SONG_POSITION
$NI_TRANSPORT_RUNNING
$NOTE_HELD
$NUM_GROUPS
$NUM_OUTPUT_CHANNELS
$NUM_ZONES
$PLAYED_VOICES_INST
$PLAYED_VOICES_TOTAL
$POLY_AT_NUM
$REF_GROUP_IDX
$RPN_ADDRESS
$RPN_VALUE
$SIGNATURE_DENOM
$SIGNATURE_NUM
$START_CRITERIA_AND_NEXT
$START_CRITERIA_AND_NOT_NEXT
$START_CRITERIA_CYCLE_RANDOM
$START_CRITERIA_CYCLE_ROUND_ROBIN
$START_CRITERIA_NONE
$START_CRITERIA_ON_CONTROLLER
$START_CRITERIA_ON_KEY
$START_CRITERIA_OR_NEXT
$START_CRITERIA_SLICE_TRIGGER
$UI_WAVEFORM_TABLE_IS_BIPOLAR
$UI_WAVEFORM_USE_MIDI_DRAG
$UI_WAVEFORM_USE_SLICES
$UI_WAVEFORM_USE_TABLE
$UI_WF_PROP_FLAGS
$UI_WF_PROP_MIDI_DRAG_START_NOTE
$UI_WF_PROP_PLAY_CURSOR
$UI_WF_PROP_TABLE_IDX_HIGHLIGHT
$UI_WF_PROP_TABLE_VAL
$VALUE_EDIT_MODE_NOTE_NAMES
$VCC_MONO_AT
$VCC_PITCH_BEND
%CC
%CC_TOUCHED
%EVENT_PAR
%GROUPS_AFFECTED
%GROUPS_SELECTED
%KEY_DOWN
%KEY_DOWN_OCT
%NOTE_DURATION
%POLY_AT
!NOTE_NAME
!CC_NAME
$MAX_ARRAY_SIZE
$ON
$OFF
$YES
$NO
$TRUE
$FALSE
$_MAX_KSP_VALUE
$NORMAL
$INVERT
$SORT_ASC
$SORT_DESC
$ALL_ROWS
$0_dB_12
$0_dB_24
$ALL_FAMILIES
$ALL_TYPES
$SWITCHES
$BUTTONS
$KNOBS
$TEXT_LABELS
$PIC_LABELS
$MENUS
$FILE_SELECTOR
$VALUE_EDITS
$SLIDERS
$TABLES
$CONSOLE.WHITE
$CONSOLE.LIGHTGREY
$CONSOLE.GREY1
$CONSOLE.GREY2
$CONSOLE.DARKGREY1
$CONSOLE.DARKGREY2
$CONSOLE.BLACK
$CONSOLE.YELLOW
$CONSOLE.RED
$REGULAR.WHITE
$REGULAR.LIGHTGREY
$REGULAR.GREY1
$REGULAR.GREY2
$REGULAR.DARKGREY1
$REGULAR.DARKGREY2
$REGULAR.BLACK
$BOLD.WHITE
$BOLD.LIGHTGREY
$BOLD.GREY1
$BOLD.GREY2
$BOLD.DARKGREY1
$BOLD.BLACK
$BOLD.YELLOW
$BOLD.RED
$LEFT
$CENTER
$LEFT_CH
$RIGHT_CH
$RIGHT
$VISIBLE
$INVISIBLE
$HORIZONTAL
$VERTICAL
$DEBUG.custom_ve_1
$DEBUG.custom_ve_2
$DEBUG.custom_ve_3
$DEBUG.custom_ve_4
$DEBUG.custom_ve_5
$DEBUG.custom_button_1
$DEBUG.custom_button_2
$DEBUG.custom_button_3
$DEBUG.custom_button_4
$DEBUG.custom_button_5

[functions]
END_USE_CODE()
RESET_CONDITION(<condition>)
SET_CONDITION(<condition>)
USE_CODE_IF(<condition>)
USE_CODE_IF_NOT(<condition>)
_delay_event_for_loading_slots(<unknown>)
_get_engine_par(<parameter>,<group>,<slot>,<generic>):integer
_get_engine_par_disp(<parameter>,<group>,<slot>,<generic>):string
_get_folder(<path variable>):string
_load_ir_sample(<file name>,<slot>,<generic>):integer
_num_slices(<group-index>):integer
_pgs_create_key(<key-id>,<size>)
_pgs_get_key_val(<key-id>,<index>):integer
_pgs_key_exists(<key-id>):boolean
_pgs_set_key_val(<key-id>,<index>,<value>)
_read_persistent_var(<variable>)
_reset_rls_trig_counter(<note>)
_set_engine_par(<parameter>,<value>,<group>,<slot>,<generic>)
_set_skin_offset(<offset>)
_slice_idx_loop_end(<group-index>,<loop-index>):integer
_slice_idx_loop_start(<group-index>,<loop-index>):integer
_slice_length(<group-index>,<slice-index>):integer
_slice_loop_count(<group-index>,<loop-index>):integer
_slice_start(<group-index>,<slice-index>):integer
_will_never_terminate(<event-id>)
abs(<expression>):integer
add_menu_item(<variable>,<text>,<number>)
add_text_line(<variable>,<text>)
allow_group(<group-index>)
array_equal(<array-variable>,<array-variable>):boolean
attach_level_meter(<uiID>,<groupIdx>,<slotIdx>,<channelIdx>,<busIdx>)
attach_zone(<waveform>,<zone-id>,<parameter>)
by_marks(<bit-mark>):integer
cc_delivery_request(<controller-number>)
change_listener_par(<signal_type>,<parameter>)
change_note(<ID-number>,<new-note-number>)
change_pan(<ID-number>,<panorama>,<relative-bit>)
change_time_with_pitch(<ID-number>,<time>):integer
change_tune(<ID-number>,<tune-amount>,<relative-bit>)
change_velo(<ID-number>,<new-velocity-number>)
change_vol(<ID-number>,<volume>,<relative-bit>)
dec(<expression>):integer
delete_event_mark(<ID-number>,<bit-mark>)
disallow_group(<group-index>)
dont_use_machine_mode(<ID-number>):integer
event_status(<ID-number>):integer
exit()
fade_in(<ID-number>,<fade-time>)
fade_out(<ID-number>,<fade-time>,<stop-voice>)
find_group(<group-name>):integer
find_mod(<group-idx>,<mod-name>):integer
find_target(<group-idx>,<mod-idx>,<target-name>):integer
find_zone(<sample-name>):integer
fs_get_filename(<ui-ID>,<return-parameter>):string
fs_navigate(<ui-ID>,<direction>)
get_control_arr(<ui-ID>,<control-parameter>):integer
get_control_par(<ui-ID>,<control-parameter>):integer
get_control_par_arr(<ui-ID>,<control-parameter>,<index>):integer
get_control_par_str(<ui-ID>,<control-parameter>):string
get_engine_par(<parameter>,<group>,<slot>,<generic>):integer
get_engine_par_disp(<parameter>,<group>,<slot>,<generic>):string
get_engine_par_disp_m(<unknown>):string
get_engine_par_m(<unknown>)
get_event_ids(<array-variable>)
get_event_par(<ID-number>,<parameter>):integer
get_event_par_arr(<ID-number>,<parameter>,<group-idx>):integer
get_folder(<path variable>):string
get_key_color(<note-number>):integer
get_key_name(<note-number>):integer
get_key_triggerstate(<note-number>):integer
get_key_type(<note-number>):integer
get_keyrange_min_note(<note-number>):integer
get_keyrange_max_note(<note-number>):integer
get_keyrange_name(<note-number>):integer
get_menu_item_str(<menu_id>,<index>):string
get_menu_item_value(<menu_id>,<index>):integer
get_menu_item_visibility(<menu_id>,<index>):integer
get_purge_state(<group-index>):integer
get_sample_length(<zone-ID>):integer
get_ui_id(<variable>):integer
get_ui_wf_property(<waveform>,<property>,<index>):integer
group_name(<group-index>):string
hide_part(<variable>,<value>)
ignore_controller()
ignore_event(<ID-number>)
ignore_midi()
in_range(<expression>,<lower>,<upper>):boolean
inc(<expression>)
load_array(<array-or-string-array-variable>,<mode>):integer
load_array_str(<array-or-string-array-variable>,<path-text>):integer
load_ir_sample(<file name>,<slot>,<generic>):integer
load_ir_sample_m(<unknown>)
load_midi_file(<path variable>):integer
load_patch(<text>,<channel>)
lsb(<variable>):integer
make_instr_persistent(<variable>)
make_perfview()
make_persistent(<variable>)
message(<number variable or text>)
mf_get_buffer_size():integer
mf_get_byte_one():integer
mf_get_byte_two():integer
mf_get_channel():integer
mf_get_command():integer
mf_get_event_par(<event-id>,<parameter>):integer
mf_get_first(<track-index>)
mf_get_id():integer
mf_get_last(<track-index>)
mf_get_length():integer
mf_get_mark(<event-id>,<mark>):integer
mf_get_next(<track-index>)
mf_get_next_at(<track-index>,<pos>)
mf_get_num_tracks():integer
mf_get_pos():integer
mf_get_prev(<track-index>)
mf_get_prev_at(<track-index>,<pos>)
mf_get_track_idx():integer
mf_insert_event(<track>,<pos>,<command>,<byte1>,<byte2>):integer
mf_insert_file(<path>,<track-offset>,<position-offset>,<mode>):integer
mf_remove_event(<event-id>)
mf_reset()
mf_set_buffer_size(<size>)
mf_set_byte_one(<par>)
mf_set_byte_two(<par>)
mf_set_channel(<midi-channel>)
mf_set_command(<par>)
mf_set_event_par(<event-id>,<parameter>,<value>)
mf_set_export_area(<name>,<start-pos>,<end-pos>,<start-track>,<end-track>)
mf_set_length(<par>)
mf_set_mark(<event-id>,<mark>,<status>)
mf_set_pos(<par>)
move_control(<variable>,<xpos>,<ypos>)
move_control_px(<variable>,<x-position>,<y-position>)
ms_to_ticks(<microseconds>):integer
msb(<variable>):integer
note_off(<ID-number>)
num_elements(<array-variable>):integer
num_slices(<group-index>):integer
num_slices_zone(<zone-id>):integer
output_channel_name(<output-number>):integer
pgs_create_key(<key-id>,<size>)
pgs_create_str_key(<key-id>)
pgs_get_key_val(<key-id>,<index>):integer
pgs_get_str_key_val(<key-id>):string
pgs_key_exists(<key-id>):boolean
pgs_set_key_val(<key-id>,<index>,<value>)
pgs_set_str_key_val(<key-id>,<text>)
pgs_str_key_exists(<key-id>):boolean
play_note(<note-number>,<velocity>,<sample-offset>,<duration>):integer
purge_group(<group-index>,<mode>)
random(<min>,<max>):integer
read_persistent_var(<variable>)
redirect_midi(<unknown>)
redirect_output(<unknown>)
remove_keyrange(<key-number>)
reset_engine()
reset_ksp_timer()
reset_rls_trig_counter(<note>)
save_array(<array-or-string-array-variable>,<mode>):integer
save_array_str(<array-or-string-array-variable>,<path-text>):integer
save_midi_file(<path variable>):integer
search(<array-variable>,<value>):integer
set_control_arr(<ui-ID>,<control-parameter>,<value>)
set_control_help(<variable>,<text>)
set_control_par(<ui-ID>,<control-parameter>,<value>)
set_control_par_arr(<ui-ID>,<control-parameter>,<value>,<index>)
set_control_par_str(<ui-ID>,<control-parameter>,<text>)
set_controller(<controller-number>,<controller-value>)
set_engine_par(<parameter>,<value>,<group>,<slot>,<generic>)
set_engine_par_disp_m(<unknown>)
set_engine_par_m(<unknown>)
set_event_mark(<ID-number>,<bit-mark>)
set_event_par(<ID-number>,<index>,<value>)
set_event_par_arr(<ID-number>,<parameter>,<value>,<group-idx>)
set_event_par_arr(<ID-number>,<parameter>,<value>,<group-idx>)
set_key_color(<note-number>,<key-color-constant>)
set_key_name(<key-number>,<key-name>)
set_key_pressed(<key-number>,<value>)
set_key_pressed_support(<value>)
set_key_type(<note-number>,key_type_constant>)
set_keyrange(<key-number1>,<key-number2>,<range-name>)
set_knob_defval(<knob-variable>,<value>)
set_knob_label(<knob-variable>,<text>)
set_knob_unit(<knob-variable>,<unit>)
set_listener(<signal_type>,<parameter>)
set_menu_item_str(<menu-id>,<index>,<text>)
set_menu_item_value(<menu-id>,<index>,<value>)
set_menu_item_visibility(<menu-id>,<index>,<visibility>)
set_midi(<channel>,<command>,<byte1>,<byte2>)
set_nrpn(<address>,<value>)
set_rpn(<address>,<value>)
set_script_title(<text>)
set_skin_offset(<offset>)
set_snapshot_type(<type>)
set_table_steps_shown(<array-variable>,<num-steps>)
set_text(<variable>,<text>)
set_ui_height(<height>)
set_ui_height_px(<height>)
set_ui_wf_property(<waveform>,<property>,<index>,<value>)
sh_left(<expression>,<amount>):integer
sh_right(<expression>,<amount>):integer
show_library_tab()
slice_idx_loop_end(<group-index>,<loop-index>):integer
slice_idx_loop_start(<group-index>,<loop-index>):integer
slice_length(<group-index>,<slice-index>):integer
slice_loop_count(<group-index>,<loop-index>):integer
slice_start(<group-index>,<slice-index>):integer
sort(<array-variable>,<direction>)
stop_wait(<callbackID>,<par>)
ticks_to_ms(<ticks>):integer
unload_slot(<unknown>)
wait(<wait-time>)
wait_ticks(<wait-time>)
will_never_terminate(<event-id>)
zone_slice_idx_loop_end(<zone-ID>,<loop-index>):integer
zone_slice_idx_loop_start(<zone-ID>,<loop-index>):integer
zone_slice_length(<zone-ID>,<slice-index>):integer
zone_slice_loop_count(<zone-ID>,<loop-index>):integer
zone_slice_start(<zone-ID>,<slice-index>):integer
create_button(<name>,<fam>,<x>,<y>,<w>,<h>,<default>,<text>,<picture>)
create_switch(<name>,<fam>,<x>,<y>,<w>,<h>,<default>,<text>,<picture>)
create_text_label(<name>,<fam>,<x>,<y>,<w>,<h>,<text>,<font>,<alignment>,<background>)
create_pic_label(<name>,<fam>,<x>,<y>,<w>,<h>,<picture>)
create_slider(<name>,<fam>,<x>,<y>,<w>,<h>,<min>,<max>,<default>,<mouse-behaviour>,<picture>)
create_knob(<name>,<fam>,<x>,<y>,<min>,<max>,<default>,<disp-ratio>,<unit>,<text>)
create_menu(<name>,<fam>,<x>,<y>,<w>,<h>,<default>,<entries>,<picture>)
create_value_edit(<name>,<fam>,<x>,<y>,<w>,<min>,<max>,<default>,<disp-ratio>,<font>,<picture>)
create_file_selector(<name>,<fam>,<x>,<y>,<w>,<h>,<col-width>,<file-type>,<root-folder>,<font>)
create_table(<name>,<fam>,<x>,<y>,<w>,<h>,<columns>,<range>)
create_waveform(<name>,<fam>,<x>,<y>,<w>,<h>,<zone-name>, <zone-flags>)
create_level_meter(<name>,<fam>,<x>,<y>,<w>,<h>,<orientation>,<group>,<slot>,<channel>,<bus>)

[functions_with_forced_parenthesis]
mf_reset

[keywords]
_pgs_changed
and
call
case
const
controller
declare
downto
else
end
end family
end for
end function
end if
end macro
end on
end property
end select
end taskfunc
end while
family
for
function
if
import
init
macro
midi_in
not
note
nrpn
on
on async_complete
on controller
on init
on listener
on midi_in
on note
on nrpn
on persistence_changed
on pgs_changed
on poly_at
on release
on rpn
on ui_control
on ui_update
or
out
override
pgs_changed
poly_at
property
release
rpn
select
step
taskfunc
to
ui_control
ui_update
var
while

[string_typed_control_parameters]
$CONTROL_PAR_AUTOMATION_NAME
$CONTROL_PAR_BASEPATH
$CONTROL_PAR_FILEPATH
$CONTROL_PAR_HELP
$CONTROL_PAR_LABEL
$CONTROL_PAR_PICTURE
$CONTROL_PAR_TEXT
$CONTROL_PAR_TEXTLINE
'''
